### ISSUE TITLE
EcoBosses support doesnt' work

### ISSUE THREAD

**Issue by krfcm** [OhTheDungeon/OhTheDungeon#75] opened 2022-06-25 16:01 UTC
**Version**
1. Spigot/Paper Version
Purpur 1671
2. Plugin Version
19_Grain_in_Ear_P1

**Describe the bug**
OTD don't see EcoBosses when server is starting.
"[Oh The Dungeons Youll Go] EcoBosses not installed, will disable BossPlugin EcoBosses features"
But i have instaled EcoBosses

**To Reproduce**
instal OTD and EcoBosses

**Expected behavior**

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://prnt.sc/1VTtyUlIapEW)

**Comment by OhTheDungeon** [comment] 2022-06-25 16:29
duplicate of https://github.com/OhTheDungeon/OhTheDungeon/issues/73

**Closed by OhTheDungeon** 2022-06-25 16:29 UTC
